Traceback (most recent call last):
  File "/home/ubuntu/hotel-management-backend/venv/bin/daphne", line 7, in <module>
    sys.exit(CommandLineInterface.entrypoint())
  File "/home/ubuntu/hotel-management-backend/venv/lib/python3.10/site-packages/daphne/cli.py", line 171, in entrypoint
    cls().run(sys.argv[1:])
  File "/home/ubuntu/hotel-management-backend/venv/lib/python3.10/site-packages/daphne/cli.py", line 233, in run
    access_log_stream = open(args.access_log, "a", 1)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/logs/daphne_access.log'
Traceback (most recent call last):
  File "/home/ubuntu/hotel-management-backend/venv/bin/daphne", line 7, in <module>
    sys.exit(CommandLineInterface.entrypoint())
  File "/home/ubuntu/hotel-management-backend/venv/lib/python3.10/site-packages/daphne/cli.py", line 171, in entrypoint
    cls().run(sys.argv[1:])
  File "/home/ubuntu/hotel-management-backend/venv/lib/python3.10/site-packages/daphne/cli.py", line 233, in run
    access_log_stream = open(args.access_log, "a", 1)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/logs/daphne_access.log'
Traceback (most recent call last):
  File "/home/ubuntu/hotel-management-backend/venv/bin/daphne", line 7, in <module>
    sys.exit(CommandLineInterface.entrypoint())
  File "/home/ubuntu/hotel-management-backend/venv/lib/python3.10/site-packages/daphne/cli.py", line 171, in entrypoint
    cls().run(sys.argv[1:])
  File "/home/ubuntu/hotel-management-backend/venv/lib/python3.10/site-packages/daphne/cli.py", line 233, in run
    access_log_stream = open(args.access_log, "a", 1)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/logs/daphne_access.log'
